seed: 1337
device: "cuda"

data:
  train_dir: "data/train"
  val_dir: "data/val"
  # image_size: 128
  image_size: 64
  context_frames: 4
  pred_frames: 1
  stride: 1

vqvae:
  in_channels: 1
  hidden: 128
  embedding_dim: 64
  num_embeddings: 512
  commitment_cost: 0.25
  # commitment_cost: 0.05

transformer:
  n_layers: 6
  n_heads: 8
  d_model: 256
  dropout: 0.1

train:
  # batch_size: 16
  batch_size: 2
  # num_workers: 4
  num_workers: 0
  # lr: 2.0e-4
  # lr: 5.0e-5
  lr: 1.0e-5
  epochs_vqvae: 20
  epochs_transformer: 20
  grad_clip: 1.0

sampling:
  temperature: 1.0
  top_k: 50

infer:
  seq_dir: "data/val/seq_0100"   # IMPORTANT: put a real folder here
  out_dir: "outputs"
  out_name: "pred_next.png"